import type { Event, Booking, UserProfile } from './types';

export const allEvents: Event[] = [
  {
    id: '1',
    title: 'Jailer',
    category: 'Movie',
    date: '2024-10-15',
    time: '19:00',
    venue: 'Metro Cinemas',
    price: 15,
    imageUrl: 'https://th.bing.com/th/id/OIP.ZbW_Wl4-0agrWCuwCdJzggHaLk?w=200&h=312&c=7&r=0&o=7&cb=ucfimg2&dpr=1.3&pid=1.7&rm=3&ucfimg=1',
    imageHint: 'action movie',
    synopsis: 'A retired jailer goes on a manhunt to find his son\'s killers. But the road leads him to a familiar, dark path.',
    seating: { rows: 8, cols: 12, unavailable: ['C5', 'C6', 'D10', 'F8'] },
  },
  {
    id: '2',
    title: 'Param Sundari',
    category: 'Movie',
    date: '2024-10-18',
    time: '21:00',
    venue: 'Grand Cineplex',
    price: 18,
    imageUrl: 'https://images.filmibeat.com/ph-big/2025/06/param-sundari1749121161_0.jpeg',
    imageHint: 'thriller movie',
    synopsis: 'A cafe owner becomes a local hero, but his past actions stir a world of trouble from a drug cartel who claim he was once one of them.',
    seating: { rows: 6, cols: 10, unavailable: ['A1', 'B5', 'E7', 'E8'] },
  },
  {
    id: '3',
    title: 'Vikram',
    category: 'Movie',
    date: '2024-10-20',
    time: '20:00',
    venue: 'Prestige Theaters',
    price: 20,
    imageUrl: 'https://th.bing.com/th/id/OIP.IvYFsRsfF1ENNumLVDZbbQHaLH?w=204&h=306&c=7&r=0&o=7&cb=ucfimg2&dpr=1.3&pid=1.7&rm=3&ucfimg=1',
    imageHint: 'spy action',
    synopsis: 'A special agent investigates a murder committed by a masked group of serial killers. However, a tangled web of clues leads him to the drug kingpin of Chennai.',
    seating: { rows: 9, cols: 15, unavailable: ['G1', 'G2', 'H5', 'I12'] },
  },
  {
    id: '4',
    title: 'Ponniyin Selvan',
    category: 'Movie',
    date: '2024-10-22',
    time: '18:30',
    venue: 'Royal Picturehouse',
    price: 22,
    imageUrl: 'https://tse1.mm.bing.net/th/id/OIP.yc2udXvfdvvHRsG9-7U0wAHaLH?cb=ucfimg2&ucfimg=1&rs=1&pid=ImgDetMain&o=7&rm=3',
    imageHint: 'historical drama',
    synopsis: 'Vandiyathevan sets out to cross the Chola land to deliver a message from the Crown Prince Aditha Karikalan. The land is rife with conspiracies and he is tasked with a mission that could change the fate of the Chola dynasty.',
    seating: { rows: 10, cols: 10, unavailable: ['B2', 'C8', 'D4', 'J9'] },
  },
  {
    id: '5',
    title: 'Beast',
    category: 'Movie',
    date: '2024-10-25',
    time: '19:30',
    venue: 'CityPlex',
    price: 16,
    imageUrl: '/images/beast.jpg',
    imageHint: 'hostage thriller',
    synopsis: 'A former RAW agent is trapped in a shopping mall when it is hijacked by terrorists. He must now single-handedly take them all down to save the hostages.',
    seating: { rows: 7, cols: 14, unavailable: ['A4', 'C9', 'F11', 'G2'] },
  },
  {
    id: '6',
    title: 'Master',
    category: 'Movie',
    date: '2024-10-28',
    time: '20:30',
    venue: 'Star Theaters',
    price: 17,
    imageUrl: '/images/master.jpg',
    imageHint: 'college action',
    synopsis: 'An alcoholic professor is sent to a juvenile school, where he clashes with a gangster who uses the children for criminal activities.',
    seating: { rows: 8, cols: 10, unavailable: ['E1', 'E2', 'F5', 'H7'] },
  },
];

export const userProfile: UserProfile = {
    name: 'Alex Ray',
    email: 'alex.ray@example.com',
    preferences: ['sci-fi', 'rock music', 'thrillers'],
    pastBookings: [
        { eventId: '1', eventTitle: 'Galaxy Runners', bookingDate: '2024-07-01'},
        { eventId: '2', eventTitle: 'The Crimson Heist', bookingDate: '2024-07-10'},
    ],
};


export const userBookings: Booking[] = [
    {
        id: 'booking1',
        eventId: '3',
        eventTitle: 'Echoes of the Void',
        eventDate: '2024-09-05',
        eventImageUrl: '/images/concert1.jpg',
        seats: ['D5', 'D6'],
        totalPrice: 150,
        bookingDate: '2024-08-01',
    },
    {
        id: 'booking2',
        eventId: '7',
        eventTitle: 'Championship Finals',
        eventDate: '2024-09-22',
        eventImageUrl: '/images/sports1.jpg',
        seats: ['Section 102, Row G, Seat 12', 'Section 102, Row G, Seat 13'],
        totalPrice: 240,
        bookingDate: '2024-08-10',
    }
]
